apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service
  namespace: comms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      labels:
        app: chat-service
    spec:
      containers:
        - name: chat-service
          image: chat-service:latest
          ports:
            - containerPort: 4567
          env:
            - name: RABBITMQ_URL
              value: "amqp://rabbitmq:5672"
---
apiVersion: v1
kind: Service
metadata:
  name: chat-service
spec:
  selector:
    app: chat-service
  ports:
    - protocol: TCP
      port: 4567
      targetPort: 4567
  type: ClusterIP