apiVersion: apps/v1
kind: Deployment
metadata:
  name: logging-service
  namespace: comms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logging-service
  template:
    metadata:
      labels:
        app: logging-service
    spec:
      containers:
        - name: logging-service
          image: logging-service:latest
          ports:
            - containerPort: 4569
          env:
            - name: RABBITMQ_URL
              value: "amqp://rabbitmq:5672"
            - name: POSTGRES_URL
              value: "postgres://demo:demo@postgres:5432/demo"
---
apiVersion: v1
kind: Service
metadata:
  name: logging-service
  namespace: comms
spec:
  selector:
    app: logging-service
  ports:
    - protocol: TCP
      port: 4569
      targetPort: 4569
  type: ClusterIP