apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: comms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: notification-service:latest
          ports:
            - containerPort: 4568
          env:
            - name: RABBITMQ_URL
              value: "amqp://rabbitmq:5672"
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: comms
spec:
  selector:
    app: notification-service
  ports:
    - protocol: TCP
      port: 4568
      targetPort: 4568
  type: ClusterIP